# Generated by Django 6.0 on 2025-12-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='card_last_4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
