# Generated by Django 6.0 on 2025-12-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_companyprofile_card_brand_companyprofile_card_last_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='rank',
            field=models.CharField(choices=[('S', 'S-Class'), ('A', 'A-Class'), ('B', 'B-Class'), ('C', 'C-Class')], default='C', max_length=2),
        ),
    ]
