# Generated by Django 6.0 on 2026-01-02 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_clubprofile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadowuser',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shadowuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shadow_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
