# Generated by Django 6.1 on 2026-09-13 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_shadowuser_is_claimed_shadowuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('CLUB', 'Club'), ('ADMIN', 'Admin'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('domain_focus', models.CharField(choices=[('SOFTWARE_DEV', 'Software Development'), ('MARKETING', 'Digital Marketing'), ('BOTH', 'Both Domains')], default='SOFTWARE_DEV', max_length=20)),
                ('verification_status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING_VERIFICATION', max_length=25)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='student_docs/')),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('club_affiliation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('club_affiliation_role', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
