# Generated by Django 6.1 on 2026-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_terms_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='duitnow_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
