# Generated by Django 6.1 on 2026-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_studentprofile_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/clubs/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/companies/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/students/'),
        ),
    ]
