# Generated by Django 6.1 on 2026-10-03 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.CharField(choices=[('TALENT', 'Talent Agreement'), ('CLIENT', 'Client Service Agreement')], max_length=20)),
                ('version', models.CharField(max_length=40)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'agreement', 'version'), name='unique_agreement_acceptance')],
            },
        ),
    ]
