# Generated by Django 6.0 on 2025-12-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='requirements',
            field=models.JSONField(default=list),
        ),
    ]
