# Generated by Django 6.0 on 2025-12-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
