# Generated by Django 6.0 on 2026-01-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWARDED', 'Awarded'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('NOT_SELECTED', 'Not Selected')], default='PENDING', max_length=20),
        ),
    ]
