# Generated by Django 6.1 on 2026-09-13 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_application_status'),
        ('users', '0006_alter_user_role_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_jobs', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_match_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='match_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='project_outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='software_sub_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Applications / Matching'), ('MATCHED', 'Matched (Pending Finalization)'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('TALENT_BOUNTY', 'Talent Bounty'), ('BRAND_AMBASSADOR', 'Brand Ambassador'), ('SOFTWARE_DEVELOPMENT', 'Software Development'), ('DIGITAL_MARKETING', 'Digital Marketing')], max_length=30),
        ),
        migrations.CreateModel(
            name='ClientAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='client_assets/')),
                ('asset_type', models.CharField(choices=[('DOCUMENT', 'Document / Brief'), ('BRAND', 'Brand Asset'), ('RAW_VIDEO', 'Raw Video Footage'), ('OTHER', 'Other')], default='DOCUMENT', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assets', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='student_deliverables/')),
                ('contribution_role', models.CharField(blank=True, max_length=150)),
                ('contribution_summary', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_deliverables', to='campaigns.campaign')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='users.studentprofile')),
            ],
        ),
    ]
