# Generated by Django 6.1 on 2026-09-13 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaign_assigned_students_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientasset',
            name='asset_type',
            field=models.CharField(choices=[('DOCUMENT', 'Document / Brief'), ('BRAND', 'Brand Asset / Vector'), ('RAW_VIDEO', 'Raw Video Footage (4K/HD)'), ('RAW_PHOTO', 'Raw Lifestyle Photography'), ('AUDIO_STEM', 'Audio Stem / Jingle'), ('OTHER', 'Other')], default='DOCUMENT', max_length=20),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('percentage', models.PositiveSmallIntegerField(default=33)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_revisions', models.PositiveSmallIntegerField(default=2)),
                ('revisions_used', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted (Under Review)'), ('REVISION_REQUESTED', 'Revision Requested'), ('APPROVED', 'Approved (Escrow Released)')], default='PENDING', max_length=30)),
                ('deliverable_url', models.URLField(blank=True, null=True)),
                ('deliverable_file', models.FileField(blank=True, null=True, upload_to='milestone_deliverables/')),
                ('deliverable_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp_tag', models.CharField(blank=True, max_length=100)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='collaboration_files/')),
                ('is_revision_request', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaigns.milestone')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
