# Generated by Django 6.1 on 2026-09-14 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_clientasset_asset_type_milestone_and_more'),
        ('users', '0006_alter_user_role_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254)),
                ('role_in_project', models.CharField(default='Collaborator', max_length=150)),
                ('payout_share_percentage', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to='campaigns.campaign')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_team_invitations', to='users.studentprofile')),
                ('invitee_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_team_invitations', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
