# Generated by Django 6.0.6 on 2026-09-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_projectteaminvitation'),
        ('users', '0007_user_terms_accepted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn by admin')], default='PENDING', max_length=20)),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_offers', to='campaigns.campaign')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_offers', to='users.studentprofile')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'student'), name='unique_match_offer_per_student')],
            },
        ),
    ]
