# Generated by Django 6.1 on 2026-09-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_match_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='payment_structure',
            field=models.CharField(choices=[('UPFRONT', 'Upfront (full project fee before work starts)'), ('MANUAL', 'Manual (admin logs client payments as they arrive)')], default='UPFRONT', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the default platform cut for this campaign (e.g. 10.00 = 10%). Leave blank to use the site default.', max_digits=5, null=True),
        ),
    ]
