# Generated by Django 6.1 on 2026-09-23 10:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaign_payment_structure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='platform_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the default platform cut for this campaign (e.g. 10.00 = 10%). Leave blank to use the site default.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5),
        ),
    ]
