# Generated by Django 6.1 on 2026-09-25 15:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_alter_campaign_platform_fee_percent_and_more'),
        ('users', '0009_clubprofile_logo_companyprofile_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectImpactReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('business_pain_point', models.TextField(blank=True)),
                ('client_industry', models.CharField(blank=True, max_length=120)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('verified_skills', models.JSONField(blank=True, default=list)),
                ('testimonial', models.TextField(blank=True)),
                ('signer_name', models.CharField(blank=True, max_length=150)),
                ('signer_title', models.CharField(blank=True, max_length=150)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_report', to='campaigns.campaign')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_impact_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(editable=False, max_length=32, unique=True)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('technical_solution', models.TextField(blank=True)),
                ('proof_url', models.URLField(blank=True)),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='ledger_proof/')),
                ('before_caption', models.CharField(blank=True, max_length=150)),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='ledger_proof/')),
                ('after_caption', models.CharField(blank=True, max_length=150)),
                ('student_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_ledgers', to='campaigns.campaign')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_ledgers', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_ledgers', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'student')},
            },
        ),
    ]
