# Generated by Django 6.1 on 2026-10-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_campaign_completed_at_campaign_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='auto_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
