# Generated by Django 6.1 on 2026-09-18 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_match_offer'),
        ('payments', '0002_initial'),
        ('users', '0008_studentprofile_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Bank Details'), ('PROCESSING', 'Ready for Disbursement'), ('PAID', 'Disbursed'), ('FAILED', 'Disbursement Failed')], default='PROCESSING', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=255)),
                ('duitnow_id', models.CharField(blank=True, max_length=50)),
                ('transfer_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='campaigns.campaign')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='users.studentprofile')),
            ],
        ),
    ]
