# Generated by Django 6.1 on 2026-09-23 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaign_payment_structure_and_more'),
        ('payments', '0003_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='campaigns.milestone'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('FINDERS_FEE', 'Finders Fee'), ('SUBSCRIPTION', 'Subscription'), ('PROJECT_FEE', 'Project Fee')], max_length=20),
        ),
    ]
