# Generated by Django 6.1 on 2026-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_alter_campaign_platform_fee_percent_and_more'),
        ('payments', '0004_payout_milestone_alter_transaction_transaction_type'),
        ('users', '0009_clubprofile_logo_companyprofile_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='bank_details_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(condition=models.Q(('milestone__isnull', False)), fields=('campaign', 'student', 'milestone'), name='unique_payout_per_student_milestone'),
        ),
    ]
