# Generated by Django 6.1 on 2026-09-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payout_bank_details_changed_at_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.CharField(blank=True, choices=[('MOCK', 'Demo checkout'), ('TOYYIBPAY', 'ToyyibPay (FPX)'), ('MANUAL', 'Recorded by admin')], max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_bill_code',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
