# Generated by Django 6.1 on 2026-10-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_transaction_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
