# Generated by Django 6.0.6 on 2026-10-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_campaign_completed_at_campaign_started_at_and_more'),
        ('payments', '0007_transaction_is_test'),
        ('users', '0010_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ISSUED', 'Awaiting payment'), ('PAID', 'Paid'), ('VOID', 'Replaced')], default='ISSUED', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bill_to_name', models.CharField(max_length=255)),
                ('bill_to_email', models.EmailField(max_length=254)),
                ('project_title', models.CharField(max_length=255)),
                ('service_fee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='campaigns.campaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='users.companyprofile')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
