"""Guards and helpers that keep demo/seed accounts (with publicly known passwords) out of production."""
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured

# Accounts created by create_seed_users.py and the local demo seed scripts
DEMO_ACCOUNT_EMAILS = [
    'admin@unipact.com', 'company@unipact.com', 'student@unipact.com', 'student2@unipact.com',
    'student3@unipact.com', 'club@unipact.com',
    'cybercorp@test.com', 'megacorp@test.com', 'technova@test.com',
    'netrunners@test.com', 'bytebuilders@test.com', 'futuredevs@test.com',
]
# Accounts generated by `manage.py seed_data`
DEMO_EMAIL_PATTERNS = [r'^company_\d+_\d+@example\.com$', r'^club_\d+_\d+@student\.edu\.my$']


def refuse_in_production(script_name):
    if settings.IS_PRODUCTION:
        raise ImproperlyConfigured(
            f'{script_name} creates demo accounts with publicly known passwords and must never run in production '
            '(DJANGO_ENV=production). Use `python manage.py create_admin` to create a real admin account.'
        )


def demo_accounts_queryset():
    from django.db.models import Q
    from users.models import User

    query = Q(email__in=DEMO_ACCOUNT_EMAILS)
    for pattern in DEMO_EMAIL_PATTERNS:
        query |= Q(email__regex=pattern)
    return User.objects.filter(query)
